# config/routes.yaml

# 1. On garde la configuration automatique pour tes anciens contrôleurs
controllers:
    resource: 
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# 2. ON FORCE la détection de ton nouveau contrôleur Mailer
mailer_test:
    path: /test-mail
    controller: App\Controller\MailerController::sendEmail